name: Node.js CI

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm run build --if-present
    - name: Upload the artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: artifact
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: version
        run: |
          echo "VERSION=$(echo $(date +%Y%m%d_%H%M))" >> $GITHUB_ENV
              
      - name: Downloading the artifacts
        uses: actions/download-artifact@v3
        with:
          name: "myArtifact_${{needs.Build.outputs.set_date}}"
          path: ./artifact

      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Build and Push the image to GHCR
        run: |
          docker login -u $GITHUB_REPOSITORY_OWNER -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker build . -t ghcr.io/canarysplayground/myshuttle:${{ env.VERSION }}     
          docker push ghcr.io/canarysplayground/myshuttle:${{ env.VERSION }}
